version: '2'
services:
    registro_gafetes-app:
        image: registro_gafetes
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://registro_gafetes-mysql:3306/registro_gafetes?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    registro_gafetes-mysql:
        extends:
            file: mysql.yml
            service: registro_gafetes-mysql
